export const STATE_OPTIONS = [
  { key: 'AP', label: 'Andhra Pradesh', value: 'Andhra Pradesh' },
  { key: 'AR', label: 'Arunachal Pradesh', value: 'Arunachal Pradesh' },
  { key: 'AS', label: 'Assam', value: 'Assam' },
  { key: 'BR', label: 'Bihar', value: 'Bihar' },
  { key: 'CT', label: 'Chhattisgarh', value: 'Chhattisgarh' },
  { key: 'GA', label: 'Goa', value: 'Goa' },
  { key: 'GJ', label: 'Gujarat', value: 'Gujarat' },
  { key: 'HR', label: 'Haryana', value: 'Haryana' },
  { key: 'HP', label: 'Himachal Pradesh', value: 'Himachal Pradesh' },
  { key: 'JH', label: 'Jharkhand', value: 'Jharkhand' },
  { key: 'KA', label: 'Karnataka', value: 'Karnataka' },
  { key: 'KL', label: 'Kerala', value: 'Kerala' },
  { key: 'MP', label: 'Madhya Pradesh', value: 'Madhya Pradesh' },
  { key: 'MH', label: 'Maharashtra', value: 'Maharashtra' },
  { key: 'MN', label: 'Manipur', value: 'Manipur' },
  { key: 'ML', label: 'Meghalaya', value: 'Meghalaya' },
  { key: 'MZ', label: 'Mizoram', value: 'Mizoram' },
  { key: 'NL', label: 'Nagaland', value: 'Nagaland' },
  { key: 'OD', label: 'Odisha', value: 'Odisha' },
  { key: 'PB', label: 'Punjab', value: 'Punjab' },
  { key: 'RJ', label: 'Rajasthan', value: 'Rajasthan' },
  { key: 'SK', label: 'Sikkim', value: 'Sikkim' },
  { key: 'TN', label: 'Tamil Nadu', value: 'Tamil Nadu' },
  { key: 'TS', label: 'Telangana', value: 'Telangana' },
  { key: 'TR', label: 'Tripura', value: 'Tripura' },
  { key: 'UP', label: 'Uttar Pradesh', value: 'Uttar Pradesh' },
  { key: 'UK', label: 'Uttarakhand', value: 'Uttarakhand' },
  { key: 'WB', label: 'West Bengal', value: 'West Bengal' },
];
